import React from 'react';
import { X, ShieldCheck, Info, ExternalLink, Sparkles, Wand2 } from 'lucide-react';

interface ImpressumModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const ImpressumModal: React.FC<ImpressumModalProps> = ({
  isOpen,
  onClose,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center px-6">
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-sm"
        onClick={onClose}
      />
      
      <div className="relative w-full max-w-lg bg-neutral-900 border border-white/10 rounded-3xl shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-300">
        <div className="p-8">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-indigo-600/20 rounded-xl flex items-center justify-center">
                <ShieldCheck className="w-5 h-5 text-indigo-400" />
              </div>
              <div>
                <h2 className="text-xl font-bold">Impressum</h2>
                <p className="text-xs text-neutral-500 font-mono uppercase tracking-widest">Legal & Credits</p>
              </div>
            </div>
            <button 
              onClick={onClose}
              className="p-2 hover:bg-white/5 rounded-full transition-colors"
            >
              <X className="w-6 h-6 text-neutral-500" />
            </button>
          </div>

          <div className="space-y-8">
            {/* Operator Info */}
            <div className="space-y-4">
              <h3 className="text-xs font-bold text-neutral-400 uppercase tracking-widest flex items-center gap-2">
                <Info className="w-3 h-3" /> Operator Information
              </h3>
              <div className="p-4 bg-black rounded-2xl border border-white/5 space-y-2 text-sm text-neutral-300">
                <p className="font-bold text-white">JAKEDOT.NET</p>
                <p>Digital Synthesis Division</p>
                <p>Email: contact@jakedot.net</p>
              </div>
            </div>

            {/* Technology Credits */}
            <div className="space-y-4">
              <h3 className="text-xs font-bold text-neutral-400 uppercase tracking-widest flex items-center gap-2">
                <Sparkles className="w-3 h-3" /> Technology Stack
              </h3>
              <div className="space-y-3">
                <div className="flex items-center justify-between p-4 bg-white/5 rounded-2xl border border-white/5">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-indigo-500/10 rounded-lg flex items-center justify-center">
                      <img src="https://www.gstatic.com/lamda/images/favicon_v1_150160d13988652cbf5e.svg" alt="Gemini" className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-xs font-bold">Image Creation Source</p>
                      <p className="text-[10px] text-neutral-500 uppercase font-mono">Google Gemini AI</p>
                    </div>
                  </div>
                  <a href="https://deepmind.google/technologies/gemini/" target="_blank" rel="noopener noreferrer" className="text-neutral-500 hover:text-white transition-colors">
                    <ExternalLink className="w-4 h-4" />
                  </a>
                </div>
                <div className="flex items-center justify-between p-4 bg-white/5 rounded-2xl border border-white/5">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-emerald-500/10 rounded-lg flex items-center justify-center text-emerald-500">
                      <Wand2 className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-xs font-bold">Synthesis Engine</p>
                      <p className="text-[10px] text-neutral-500 uppercase font-mono">Neural Fusion v0.6</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Disclaimer */}
            <div className="p-4 bg-amber-500/5 border border-amber-500/10 rounded-2xl">
              <p className="text-[10px] text-amber-200/60 font-mono leading-relaxed uppercase tracking-wider">
                Disclaimer: All images generated by this engine are synthesized by artificial intelligence. The operator does not claim ownership of specific character designs from the referenced anime series.
              </p>
            </div>
          </div>

          <div className="mt-10">
            <button 
              onClick={onClose}
              className="w-full py-4 bg-white text-black rounded-2xl font-bold text-sm hover:bg-neutral-200 transition-colors"
            >
              Acknowledge
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
